language: ruby
branches:
  only:
    - master
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby-19mode
  - jruby-20mode
  
script: bundle exec rspec

matrix:
  allow_failures:
    - rvm: 2.1.0